### ISSUE TITLE
Einstellungen Arbeitsbereiche doppelt

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/iqb-berlin.github.io#10]

**Comment by tobhu1981** [comment]
Ne Kleinigkeit, vielleicht kann man das auch so lassen: Es gibt in den Bereichsgruppen Einstellungen zu den Arbeitsbreichen: ![grafik](https://user-images.githubusercontent.com/78656991/182310150-e3dee07d-4180-4227-a7d0-9cb3095d3920.png). Diese Einstellungen sind dann noch einmal zu finden direkt im geöffneten Arbeitsbereich: ![grafik](https://user-images.githubusercontent.com/78656991/182310418-e134e2a9-1a2d-41ec-9063-f51df29dc8a2.png). Ist ja nicht falsch, aber vielleicht würde es an einer Stelle ausreichen? Dann vielleicht an der übergeordneten Stelle, also in den Einstellungen zur Bereichsgruppe?

**Comment by mechtelm** [comment]
Wollte ich so, damit ein schneller Zugriff möglich ist, wenn einem gerade einfällt, dass man an den Einstellungen etws ändern will. Jede/r wird seine Lieblingsstelle haben.
