### ISSUE TITLE
Die alphabetische Auflistung der Repositories in der ReadMe.md funktioniert nicht

### ISSUE THREAD

**Issue by o99un** [iqb-berlin/iqb-berlin.github.io#6]
Die alphabetische Auflistung der Repositories zeigt statt der Repositories den Quellcode hierfür

**Comment by mechtelm** [comment]
Der Quellcode ist Jekyll-Syntax und wird nie in Markdown-Dateien angezeigt. Der Zweck der Syntax hier ist die Verwendung im Rahmen von GitHub-Pages: Zusammen mit der _layouts/default.html-Datei erzeugt GitHub dann eine neue Html-Datei, in der dann auch die Syntax umgesetzt wird. Zu sehen ist dies dann hier: [https://iqb-berlin.github.io/](https://iqb-berlin.github.io/).
