### ISSUE TITLE
Testcenter Doku: Verbesserungen

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/iqb-berlin.github.io#7]
"erleichtert die Installation durch ein sog. Docker-Setup"
Was ist ein Docker Setup? Dieses Wort gibt es nicht und wenn man das erfindet muss man erklären was das sein soll.
Vorschlag: "erleichtert die Installation durch Containervirtualisierung"

"Für die Installation muss man einen Server bereitstellen (Linux oder Windows)"
Wir unterstützen kein Windows...

"Das IQB ist bemüht, die Installationspakete gut abzusichern"
Wir sicher nicht nur die Installationspakete ab, sondern die Software an sich.

"Nach der Installation ist zunächst ein Standard-Konto für die Verwaltung von Tests angelegt."
Was ist ein "Standard-Konto"? Wird nirgends erklärt und taucht auch in der Doku nie wieder auf.

"Die Texte dieser Wiki"
Wiki ist neutral (https://de.wiktionary.org/wiki/Wiki)

"Durch Anwählen der Internet-Adresse"
"Anwählen" ist eine komische Wortwahl

"Fortsetzung erst nach vollständiger Anzeige"
Anzeige deutet auf etwas visuelles hin. Hier geht aber auch im Audios. Daher lieber "Präsentation" oder ähnliches.

"nach Abbruch oder Absturz eines Computers"
Abbruch des Computers?! ;D

" (d. h. die Abfolge von Aufgaben bzw. Fragen)"
Das ist eine gute Gelegenheit das Wort "Unit" einzuführen.

**Comment by tobhu1981** [comment]
Danke fürs Feedback, ist geändert.
